services:
  telegram-media-server:
    build:
      dockerfile: Dockerfile
      context: .
    env_file: ".env"
    environment:
      - RUNNING_IN_DOCKER=true
    volumes:
      - ${MOVIE_PATH}:/app/media
    network_mode: host

  builder:
    build:
      dockerfile: dockerfile.builder
      context: .
    environment:
      - DEBIAN_ARCHS=amd64,arm64
      - ARCHLINUX_ARCHS=x86_64,aarch64
