package lang

// This file is automatically generated from messages.yaml

type MessageID string

const (
	CheckUserErrorMsgID                 MessageID = "CheckUserError"
	UnknownFileTypeMsgID                MessageID = "UnknownFileType"
	FileDownloadErrorMsgID              MessageID = "FileDownloadError"
	CheckFileExistenceErrorMsgID        MessageID = "CheckFileExistenceError"
	NotEnoughDiskSpaceMsgID             MessageID = "NotEnoughDiskSpace"
	InvalidLoginFormatMsgID             MessageID = "InvalidLoginFormat"
	LoginErrorMsgID                     MessageID = "LoginError"
	WrongPasswordMsgID                  MessageID = "WrongPassword"
	UnknownCommandMsgID                 MessageID = "UnknownCommand"
	GetMovieListErrorMsgID              MessageID = "GetMovieListError"
	InvalidIDMsgID                      MessageID = "InvalidID"
	InvalidFileIDMsgID                  MessageID = "InvalidFileID"
	MovieNotFoundMsgID                  MessageID = "MovieNotFound"
	GetFilesErrorMsgID                  MessageID = "GetFilesError"
	DeleteMovieDBErrorMsgID             MessageID = "DeleteMovieDBError"
	DeleteFilesDBErrorMsgID             MessageID = "DeleteFilesDBError"
	InvalidCommandFormatMsgID           MessageID = "InvalidCommandFormat"
	MovieListErrorMsgID                 MessageID = "MovieListError"
	MovieCheckErrorMsgID                MessageID = "MovieCheckError"
	TorrentClientErrorMsgID             MessageID = "TorrentClientError"
	AddTorrentErrorMsgID                MessageID = "AddTorrentError"
	NotEnoughSpaceMsgID                 MessageID = "NotEnoughSpace"
	GetMovieErrorMsgID                  MessageID = "GetMovieError"
	DownloadStoppedLowSpeedMsgID        MessageID = "DownloadStoppedLowSpeed"
	VideoTitleErrorMsgID                MessageID = "VideoTitleError"
	VideoDownloadErrorMsgID             MessageID = "VideoDownloadError"
	VideoExistsMsgID                    MessageID = "VideoExists"
	VideoDownloadingMsgID               MessageID = "VideoDownloading"
	TorrentDownloadStartedMsgID         MessageID = "TorrentDownloadStarted"
	FileAlreadyExistsMsgID              MessageID = "FileAlreadyExists"
	FileAddedSuccessfullyMsgID          MessageID = "FileAddedSuccessfully"
	StartCommandMsgID                   MessageID = "StartCommand"
	TorrentDownloadsStoppedMsgID        MessageID = "TorrentDownloadsStopped"
	NoMoviesMsgID                       MessageID = "NoMovies"
	LoginSuccessMsgID                   MessageID = "LoginSuccess"
	AllMoviesDeletedMsgID               MessageID = "AllMoviesDeleted"
	MovieDeletedMsgID                   MessageID = "MovieDeleted"
	DownloadVideoSuccessMsgID           MessageID = "DownloadVideoSuccess"
	MovieDownloadedMsgID                MessageID = "MovieDownloaded"
	MovieDownloadingMsgID               MessageID = "MovieDownloading"
	StartDownloadMsgID                  MessageID = "StartDownload"
	DownloadProgressMsgID               MessageID = "DownloadProgress"
	DownloadCompleteMsgID               MessageID = "DownloadComplete"
	DownloadStoppedMsgID                MessageID = "DownloadStopped"
	StartVideoDownloadMsgID             MessageID = "StartVideoDownload"
	FileSavedAsMsgID                    MessageID = "FileSavedAs"
	VideoSuccessfullyDownloadedMsgID    MessageID = "VideoSuccessfullyDownloaded"
	UnknownUserMsgID                    MessageID = "UnknownUser"
	FailedToGetFileMsgID                MessageID = "FailedToGetFile"
	FailedToDownloadFileMsgID           MessageID = "FailedToDownloadFile"
	FailedToCreateFileMsgID             MessageID = "FailedToCreateFile"
	FailedToSaveFileMsgID               MessageID = "FailedToSaveFile"
	FileDownloadedSuccessfullyMsgID     MessageID = "FileDownloadedSuccessfully"
	ErrorGettingFilesystemStatsMsgID    MessageID = "ErrorGettingFilesystemStats"
	RequiredSpaceMsgID                  MessageID = "RequiredSpace"
	AvailableSpaceMsgID                 MessageID = "AvailableSpace"
	FailedToDeleteFileMsgID             MessageID = "FailedToDeleteFile"
	FileDeletedSuccessfullyMsgID        MessageID = "FileDeletedSuccessfully"
	FailedToDeleteTorrentFileMsgID      MessageID = "FailedToDeleteTorrentFile"
	TorrentFileDeletedSuccessfullyMsgID MessageID = "TorrentFileDeletedSuccessfully"
	FailedToDeleteRootFolderMsgID       MessageID = "FailedToDeleteRootFolder"
	RootFolderDeletedSuccessfullyMsgID  MessageID = "RootFolderDeletedSuccessfully"
	MovieDeletedSuccessfullyMsgID       MessageID = "MovieDeletedSuccessfully"
	FailedToReadDirectoryMsgID          MessageID = "FailedToReadDirectory"
	DownloadDocumentErrorMsgID          MessageID = "DownloadDocumentError"
	TorrentFileExistsErrorMsgID         MessageID = "TorrentFileExistsError"
	TorrentFileDownloadErrorMsgID       MessageID = "TorrentFileDownloadError"
	StopNoArgumentMsgID                 MessageID = "StopNoArgument"
	StopInvalidIDMsgID                  MessageID = "StopInvalidID"
	StopMovieStoppedMsgID               MessageID = "StopMovieStopped"
	VPNErrorMsgID                       MessageID = "VPNError"
	VPNAlreadyEnabledMsgID              MessageID = "VPNAlreadyEnabled"
	VPNAlreadyDisabledMsgID             MessageID = "VPNAlreadyDisabled"
	VPNEnabledMsgID                     MessageID = "VPNEnabled"
	VPNDisabledMsgID                    MessageID = "VPNDisabled"
	VPNCheckErrorMsgID                  MessageID = "VPNCheckError"
	VPNChangeErrorMsgID                 MessageID = "VPNChangeError"
	VPNStatusMsgID                      MessageID = "VPNStatus"
	DownloadCancelledMsgID              MessageID = "DownloadCancelled"
	InvalidIDsMsgID                     MessageID = "InvalidIDs"
	DeletedMoviesMsgID                  MessageID = "DeletedMovies"
	StoppedDownloadsMsgID               MessageID = "StoppedDownloads"
	NoValidIDsMsgID                     MessageID = "NoValidIDs"
	VPNUsageMsgID                       MessageID = "VPNUsage"
	VPNInvalidActionMsgID               MessageID = "VPNInvalidAction"
)

var messages = map[MessageID]map[string]string{
	"CheckUserError": {
		"en": "An error occurred while checking the user. Please try again later",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0441\u043d\u043e\u0432\u0430 \u043f\u043e\u0437\u0436\u0435",
	},
	"UnknownFileType": {
		"en": "Unknown file type",
		"ru": "\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u044b\u0439 \u0442\u0438\u043f \u0444\u0430\u0439\u043b\u0430",
	},
	"FileDownloadError": {
		"en": "An error occurred while downloading the file (files larger than 50MB cannot be uploaded)",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0444\u0430\u0439\u043b\u0430 (\u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0431\u043e\u043b\u044c\u0448\u0435 50\u041c\u0411 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430)",
	},
	"CheckFileExistenceError": {
		"en": "An error occurred while checking file existence. Please try again",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043e\u0432\u0430\u043d\u0438\u044f \u0444\u0430\u0439\u043b\u0430. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0441\u043d\u043e\u0432\u0430",
	},
	"NotEnoughDiskSpace": {
		"en": "Error downloading the torrent file (not enough disk space)",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0442\u043e\u0440\u0440\u0435\u043d\u0442\u0430 (\u0432\u043e\u0437\u043c\u043e\u0436\u043d\u043e, \u043d\u0435 \u0445\u0432\u0430\u0442\u0430\u0435\u0442 \u043c\u0435\u0441\u0442\u0430 \u043d\u0430 \u0434\u0438\u0441\u043a\u0435)",
	},
	"InvalidLoginFormat": {
		"en": "Invalid command format. Use: /login [PASSWORD]",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u043a\u043e\u043c\u0430\u043d\u0434\u044b. \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435: /login [PASSWORD]",
	},
	"LoginError": {
		"en": "An error occurred during login. Please try again",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0432\u0445\u043e\u0434\u0435. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0441\u043d\u043e\u0432\u0430",
	},
	"WrongPassword": {
		"en": "Incorrect password",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u043e\u043b\u044c",
	},
	"UnknownCommand": {
		"en": "Unknown command. Use /start to get the list of available commands",
		"ru": "\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u0430\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u0430. \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 /start \u0434\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0441\u043f\u0438\u0441\u043a\u0430 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u044b\u0445 \u043a\u043e\u043c\u0430\u043d\u0434",
	},
	"GetMovieListError": {
		"en": "An error occurred while fetching the movie list. Please try again later",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0441\u043f\u0438\u0441\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u043e\u0432. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u043f\u043e\u0437\u0436\u0435",
	},
	"InvalidID": {
		"en": "Invalid ID",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 ID",
	},
	"InvalidFileID": {
		"en": "Invalid file ID",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 ID \u0444\u0430\u0439\u043b\u0430",
	},
	"MovieNotFound": {
		"en": "Movie not found",
		"ru": "\u0424\u0438\u043b\u044c\u043c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d",
	},
	"GetFilesError": {
		"en": "Error retrieving files for the movie",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0444\u0430\u0439\u043b\u043e\u0432 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u043c\u0430",
	},
	"DeleteMovieDBError": {
		"en": "Error deleting the movie record from the database",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u0438 \u0437\u0430\u043f\u0438\u0441\u0438 \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u0437 \u0431\u0430\u0437\u044b \u0434\u0430\u043d\u043d\u044b\u0445",
	},
	"DeleteFilesDBError": {
		"en": "Error deleting the movie files from the database",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u0438 \u0444\u0430\u0439\u043b\u043e\u0432 \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u0437 \u0431\u0430\u0437\u044b \u0434\u0430\u043d\u043d\u044b\u0445",
	},
	"InvalidCommandFormat": {
		"en": "Invalid command format",
		"ru": "\u041d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u043a\u043e\u043c\u0430\u043d\u0434\u044b",
	},
	"MovieListError": {
		"en": "Error getting list of movies",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0441\u043f\u0438\u0441\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u043e\u0432",
	},
	"MovieCheckError": {
		"en": "Error checking existence of movie",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043e\u0432\u0430\u043d\u0438\u044f \u0444\u0438\u043b\u044c\u043c\u0430",
	},
	"TorrentClientError": {
		"en": "Failed to create torrent client: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u0442\u044c \u0442\u043e\u0440\u0440\u0435\u043d\u0442-\u043a\u043b\u0438\u0435\u043d\u0442: %v",
	},
	"AddTorrentError": {
		"en": "Failed to add torrent: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0434\u043e\u0431\u0430\u0432\u0438\u0442\u044c \u0442\u043e\u0440\u0440\u0435\u043d\u0442: %v",
	},
	"NotEnoughSpace": {
		"en": "Not enough space to download movie %s",
		"ru": "\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043c\u0435\u0441\u0442\u0430 \u0434\u043b\u044f \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0444\u0438\u043b\u044c\u043c\u0430 %s",
	},
	"GetMovieError": {
		"en": "Error getting movie: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0444\u0438\u043b\u044c\u043c\u0430: %v",
	},
	"DownloadStoppedLowSpeed": {
		"en": "Download of movie %s stopped due to low download speed",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u0438\u0437-\u0437\u0430 \u043d\u0438\u0437\u043a\u043e\u0439 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438",
	},
	"VideoTitleError": {
		"en": "Error getting video title: %s",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u0432\u0438\u0434\u0435\u043e: %s",
	},
	"VideoDownloadError": {
		"en": "Error downloading video: %s",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0432\u0438\u0434\u0435\u043e: %s",
	},
	"VideoExists": {
		"en": "Video already exists or is in the process of downloading",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0443\u0436\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442 \u0438\u043b\u0438 \u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438",
	},
	"VideoDownloading": {
		"en": "Video is downloading!",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f!",
	},
	"TorrentDownloadStarted": {
		"en": "Torrent download has started!",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0442\u043e\u0440\u0440\u0435\u043d\u0442\u0430 \u043d\u0430\u0447\u0430\u043b\u0430\u0441\u044c!",
	},
	"FileAlreadyExists": {
		"en": "File already exists",
		"ru": "\u0424\u0430\u0439\u043b \u0443\u0436\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442",
	},
	"FileAddedSuccessfully": {
		"en": "File successfully added",
		"ru": "\u0424\u0430\u0439\u043b \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u043d",
	},
	"StartCommand": {
		"en": "<file.torrent> - download torrent\n<URL> - download streaming video\n/ls - get list of files\n/rm <ID> - delete movie, all - to delete all\n/stop <ID> - stop download, all - to stop all\n/vpnon - enable VPN\n/vpnoff - disable VPN",
		"ru": "<file.torrent> - \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c torrent\n<URL> - \u0441\u043a\u0430\u0447\u0430\u0442\u044c \u043f\u043e\u0442\u043e\u043a\u043e\u0432\u043e\u0435 \u0432\u0438\u0434\u0435\u043e\n/ls - \u043f\u043e\u043b\u0443\u0447\u0438\u0442\u044c \u0441\u043f\u0438\u0441\u043e\u043a \u0444\u0430\u0439\u043b\u043e\u0432\n/rm <ID> - \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u0444\u0438\u043b\u044c\u043c, all - \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445\n/stop <ID> - \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0443, all - \u0434\u043b\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432\u0441\u0435\u0445\n/vpnon - \u0432\u043a\u043b\u044e\u0447\u0438\u0442\u044c VPN\n/vpnoff - \u0432\u044b\u043a\u043b\u044e\u0447\u0438\u0442\u044c VPN",
	},
	"TorrentDownloadsStopped": {
		"en": "All torrent downloads have been stopped!",
		"ru": "\u0412\u0441\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0442\u043e\u0440\u0440\u0435\u043d\u0442\u043e\u0432 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u044b!",
	},
	"NoMovies": {
		"en": "The list is empty",
		"ru": "\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u0443\u0441\u0442",
	},
	"LoginSuccess": {
		"en": "Login successful",
		"ru": "\u0412\u0445\u043e\u0434 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d \u0443\u0441\u043f\u0435\u0448\u043d\u043e",
	},
	"AllMoviesDeleted": {
		"en": "All videos have been deleted",
		"ru": "\u0412\u0441\u0435 \u0432\u0438\u0434\u0435\u043e \u0443\u0434\u0430\u043b\u0435\u043d\u044b",
	},
	"MovieDeleted": {
		"en": "Movie successfully deleted",
		"ru": "\u0424\u0438\u043b\u044c\u043c \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0434\u0430\u043b\u0435\u043d",
	},
	"DownloadVideoSuccess": {
		"en": "Video downloaded successfully",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0441\u043a\u0430\u0447\u0430\u043d\u043e",
	},
	"MovieDownloaded": {
		"en": "ID: %d\nTitle: %s\nDownloaded: Yes\n\n",
		"ru": "ID: %d\n\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435: %s\n\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043d\u043e: \u0414\u0430\n\n",
	},
	"MovieDownloading": {
		"en": "ID: %d\nTitle: %s\nDownload Percentage: %d%%\n\n",
		"ru": "ID: %d\n\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435: %s\n\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438: %d%%\n\n",
	},
	"StartDownload": {
		"en": "Download started - %s",
		"ru": "\u041d\u0430\u0447\u0430\u0442\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430 - %s",
	},
	"DownloadProgress": {
		"en": "Downloading %s: %d%%",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 %s: %d%%",
	},
	"DownloadComplete": {
		"en": "Download of movie %s completed!",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430!",
	},
	"DownloadStopped": {
		"en": "Download of movie %s stopped by request",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u043f\u043e \u0437\u0430\u043f\u0440\u043e\u0441\u0443",
	},
	"StartVideoDownload": {
		"en": "Starting download for URL: %s",
		"ru": "\u041d\u0430\u0447\u0430\u043b\u043e \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0434\u043b\u044f URL: %s",
	},
	"FileSavedAs": {
		"en": "File will be saved as: %s",
		"ru": "\u0424\u0430\u0439\u043b \u0431\u0443\u0434\u0435\u0442 \u0441\u043e\u0445\u0440\u0430\u043d\u0451\u043d \u043a\u0430\u043a: %s",
	},
	"VideoSuccessfullyDownloaded": {
		"en": "Video successfully downloaded: %s",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d\u043e: %s",
	},
	"UnknownUser": {
		"en": "Please log in using the /login [PASSWORD] command",
		"ru": "\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u0435 \u0432\u0445\u043e\u0434 \u0441 \u043f\u043e\u043c\u043e\u0449\u044c\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u044b /login [PASSWORD]",
	},
	"FailedToGetFile": {
		"en": "Failed to get file: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u043e\u043b\u0443\u0447\u0438\u0442\u044c \u0444\u0430\u0439\u043b: %v",
	},
	"FailedToDownloadFile": {
		"en": "Failed to download file: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c \u0444\u0430\u0439\u043b: %v",
	},
	"FailedToCreateFile": {
		"en": "Failed to create file: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0441\u043e\u0437\u0434\u0430\u0442\u044c \u0444\u0430\u0439\u043b: %v",
	},
	"FailedToSaveFile": {
		"en": "Failed to save file: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0441\u043e\u0445\u0440\u0430\u043d\u0438\u0442\u044c \u0444\u0430\u0439\u043b: %v",
	},
	"FileDownloadedSuccessfully": {
		"en": "File downloaded successfully",
		"ru": "\u0424\u0430\u0439\u043b \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d",
	},
	"ErrorGettingFilesystemStats": {
		"en": "Error getting filesystem stats: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0441\u0442\u0430\u0442\u0438\u0441\u0442\u0438\u043a\u0438 \u0444\u0430\u0439\u043b\u043e\u0432\u043e\u0439 \u0441\u0438\u0441\u0442\u0435\u043c\u044b: %v",
	},
	"RequiredSpace": {
		"en": "Required space: %d bytes",
		"ru": "\u0422\u0440\u0435\u0431\u0443\u0435\u043c\u043e\u0435 \u043f\u0440\u043e\u0441\u0442\u0440\u0430\u043d\u0441\u0442\u0432\u043e: %d \u0431\u0430\u0439\u0442",
	},
	"AvailableSpace": {
		"en": "Available space: %d bytes",
		"ru": "\u0414\u043e\u0441\u0442\u0443\u043f\u043d\u043e\u0435 \u043f\u0440\u043e\u0441\u0442\u0440\u0430\u043d\u0441\u0442\u0432\u043e: %d \u0431\u0430\u0439\u0442",
	},
	"FailedToDeleteFile": {
		"en": "Failed to delete file %s: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u0444\u0430\u0439\u043b %s: %v",
	},
	"FileDeletedSuccessfully": {
		"en": "File %s deleted successfully",
		"ru": "\u0424\u0430\u0439\u043b %s \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0434\u0430\u043b\u0435\u043d",
	},
	"FailedToDeleteTorrentFile": {
		"en": "Failed to delete torrent file %s: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u0442\u043e\u0440\u0440\u0435\u043d\u0442-\u0444\u0430\u0439\u043b %s: %v",
	},
	"TorrentFileDeletedSuccessfully": {
		"en": "Torrent file %s deleted successfully",
		"ru": "\u0422\u043e\u0440\u0440\u0435\u043d\u0442-\u0444\u0430\u0439\u043b %s \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0434\u0430\u043b\u0435\u043d",
	},
	"FailedToDeleteRootFolder": {
		"en": "Failed to delete root folder %s: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u043a\u043e\u0440\u043d\u0435\u0432\u0443\u044e \u043f\u0430\u043f\u043a\u0443 %s: %v",
	},
	"RootFolderDeletedSuccessfully": {
		"en": "Root folder %s deleted successfully",
		"ru": "\u041a\u043e\u0440\u043d\u0435\u0432\u0430\u044f \u043f\u0430\u043f\u043a\u0430 %s \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0434\u0430\u043b\u0435\u043d\u0430",
	},
	"MovieDeletedSuccessfully": {
		"en": "Movie with ID %d and all associated files deleted successfully",
		"ru": "\u0424\u0438\u043b\u044c\u043c \u0441 ID %d \u0438 \u0432\u0441\u0435 \u0441\u0432\u044f\u0437\u0430\u043d\u043d\u044b\u0435 \u0444\u0430\u0439\u043b\u044b \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0443\u0434\u0430\u043b\u0435\u043d\u044b",
	},
	"FailedToReadDirectory": {
		"en": "Failed to read directory %s: %v",
		"ru": "\u041d\u0435 \u0443\u0434\u0430\u043b\u043e\u0441\u044c \u043f\u0440\u043e\u0447\u0438\u0442\u0430\u0442\u044c \u0434\u0438\u0440\u0435\u043a\u0442\u043e\u0440\u0438\u044e %s: %v",
	},
	"DownloadDocumentError": {
		"en": "An error occurred while uploading the file (uploading files larger than 50MB is not available)",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0444\u0430\u0439\u043b\u0430 (\u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0431\u043e\u043b\u044c\u0448\u0435 50\u041c\u0411 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430)",
	},
	"TorrentFileExistsError": {
		"en": "An error occurred while checking the existence of the file",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043e\u0432\u0430\u043d\u0438\u044f \u0444\u0430\u0439\u043b\u0430",
	},
	"TorrentFileDownloadError": {
		"en": "Error downloading torrent file",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0442\u043e\u0440\u0440\u0435\u0442 \u0444\u0430\u0439\u043b\u0430",
	},
	"StopNoArgument": {
		"en": "Please specify the movie ID or 'all' to stop all downloads.",
		"ru": "\u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u0443\u043a\u0430\u0436\u0438\u0442\u0435 ID \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u043b\u0438 'all' \u0434\u043b\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432\u0441\u0435\u0445 \u0437\u0430\u0433\u0440\u0443\u0437\u043e\u043a.",
	},
	"StopInvalidID": {
		"en": "Invalid movie ID. Please specify a valid ID or 'all'.",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 ID \u0444\u0438\u043b\u044c\u043c\u0430. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u0443\u043a\u0430\u0436\u0438\u0442\u0435 \u043a\u043e\u0440\u0440\u0435\u043a\u0442\u043d\u044b\u0439 ID \u0438\u043b\u0438 'all'.",
	},
	"StopMovieStopped": {
		"en": "Download of movie with ID %d has been stopped.",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 \u0441 ID %d \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430.",
	},
	"VPNError": {
		"en": "Error managing VPN: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0443\u043f\u0440\u0430\u0432\u043b\u0435\u043d\u0438\u0438 VPN: %v",
	},
	"VPNAlreadyEnabled": {
		"en": "VPN is already enabled",
		"ru": "VPN \u0443\u0436\u0435 \u0432\u043a\u043b\u044e\u0447\u0435\u043d",
	},
	"VPNAlreadyDisabled": {
		"en": "VPN is already disabled",
		"ru": "VPN \u0443\u0436\u0435 \u0432\u044b\u043a\u043b\u044e\u0447\u0435\u043d",
	},
	"VPNEnabled": {
		"en": "VPN has been successfully enabled",
		"ru": "VPN \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0432\u043a\u043b\u044e\u0447\u0435\u043d",
	},
	"VPNDisabled": {
		"en": "VPN has been successfully disabled",
		"ru": "VPN \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0432\u044b\u043a\u043b\u044e\u0447\u0435\u043d",
	},
	"VPNCheckError": {
		"en": "Error checking VPN status: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f VPN: %v",
	},
	"VPNChangeError": {
		"en": "Error changing VPN state: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u0438 \u0441\u043e\u0441\u0442\u043e\u044f\u043d\u0438\u044f VPN: %v",
	},
	"VPNStatus": {
		"en": "VPN status: %s",
		"ru": "\u0421\u0442\u0430\u0442\u0443\u0441 VPN: %s",
	},
	"DownloadCancelled": {
		"en": "Download canceled: %s",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u043e\u0442\u043c\u0435\u043d\u0435\u043d\u0430: %s",
	},
	"InvalidIDs": {
		"en": "Invalid IDs: %s",
		"ru": "\u041d\u0435\u0432\u0430\u043b\u0438\u0434\u043d\u044b\u0435 ID: %s",
	},
	"DeletedMovies": {
		"en": "Deleted movies with IDs: %v",
		"ru": "\u0423\u0434\u0430\u043b\u0435\u043d\u044b \u0444\u0438\u043b\u044c\u043c\u044b \u0441 ID: %v",
	},
	"StoppedDownloads": {
		"en": "Stopped downloads for movie IDs: %v",
		"ru": "\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u044b \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u043c\u043e\u0432 \u0441 ID: %v",
	},
	"NoValidIDs": {
		"en": "No valid movie IDs provided",
		"ru": "\u041d\u0435 \u043f\u0440\u0435\u0434\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u0432\u0430\u043b\u0438\u0434\u043d\u044b\u0445 ID \u0444\u0438\u043b\u044c\u043c\u043e\u0432",
	},
	"VPNUsage": {
		"en": "Usage: /vpn [on|off|status]",
		"ru": "\u0418\u0441\u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u043d\u0438\u0435: /vpn [on|off|status]",
	},
	"VPNInvalidAction": {
		"en": "Invalid action. Use 'on', 'off', or 'status'.",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u043e\u0435 \u0434\u0435\u0439\u0441\u0442\u0432\u0438\u0435. \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 'on', 'off' \u0438\u043b\u0438 'status'.",
	},
}
