package lang

// This file is automatically generated from messages.yaml

type MessageID string

const (
	CheckUserErrorMsgID              MessageID = "CheckUserError"
	LoginErrorMsgID                  MessageID = "LoginError"
	WrongPasswordMsgID               MessageID = "WrongPassword"
	UnknownCommandMsgID              MessageID = "UnknownCommand"
	GetMovieListErrorMsgID           MessageID = "GetMovieListError"
	MovieNotFoundMsgID               MessageID = "MovieNotFound"
	GetFilesErrorMsgID               MessageID = "GetFilesError"
	DeleteMovieDBErrorMsgID          MessageID = "DeleteMovieDBError"
	DeleteFilesDBErrorMsgID          MessageID = "DeleteFilesDBError"
	InvalidCommandFormatMsgID        MessageID = "InvalidCommandFormat"
	MovieCheckErrorMsgID             MessageID = "MovieCheckError"
	NotEnoughSpaceMsgID              MessageID = "NotEnoughSpace"
	DownloadStoppedLowSpeedMsgID     MessageID = "DownloadStoppedLowSpeed"
	VideoTitleErrorMsgID             MessageID = "VideoTitleError"
	VideoDownloadErrorMsgID          MessageID = "VideoDownloadError"
	VideoExistsMsgID                 MessageID = "VideoExists"
	VideoDownloadingMsgID            MessageID = "VideoDownloading"
	FileAlreadyExistsMsgID           MessageID = "FileAlreadyExists"
	StartCommandMsgID                MessageID = "StartCommand"
	TorrentDownloadsStoppedMsgID     MessageID = "TorrentDownloadsStopped"
	NoMoviesMsgID                    MessageID = "NoMovies"
	LoginSuccessMsgID                MessageID = "LoginSuccess"
	AllMoviesDeletedMsgID            MessageID = "AllMoviesDeleted"
	MovieDownloadedMsgID             MessageID = "MovieDownloaded"
	MovieDownloadingMsgID            MessageID = "MovieDownloading"
	DownloadProgressMsgID            MessageID = "DownloadProgress"
	DownloadCompleteMsgID            MessageID = "DownloadComplete"
	DownloadStoppedMsgID             MessageID = "DownloadStopped"
	VideoSuccessfullyDownloadedMsgID MessageID = "VideoSuccessfullyDownloaded"
	UnknownUserMsgID                 MessageID = "UnknownUser"
	DownloadDocumentErrorMsgID       MessageID = "DownloadDocumentError"
	TorrentFileExistsErrorMsgID      MessageID = "TorrentFileExistsError"
	TorrentFileDownloadErrorMsgID    MessageID = "TorrentFileDownloadError"
	StopNoArgumentMsgID              MessageID = "StopNoArgument"
	DownloadCancelledMsgID           MessageID = "DownloadCancelled"
	InvalidIDsMsgID                  MessageID = "InvalidIDs"
	DeletedMoviesMsgID               MessageID = "DeletedMovies"
	StoppedDownloadsMsgID            MessageID = "StoppedDownloads"
	NoValidIDsMsgID                  MessageID = "NoValidIDs"
)

var messages = map[MessageID]map[string]string{
	"CheckUserError": {
		"en": "An error occurred while checking the user. Please try again later",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u043f\u043e\u043b\u044c\u0437\u043e\u0432\u0430\u0442\u0435\u043b\u044f. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0441\u043d\u043e\u0432\u0430 \u043f\u043e\u0437\u0436\u0435",
	},
	"LoginError": {
		"en": "An error occurred during login. Please try again",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0432\u0445\u043e\u0434\u0435. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u0441\u043d\u043e\u0432\u0430",
	},
	"WrongPassword": {
		"en": "Incorrect password",
		"ru": "\u041d\u0435\u0432\u0435\u0440\u043d\u044b\u0439 \u043f\u0430\u0440\u043e\u043b\u044c",
	},
	"UnknownCommand": {
		"en": "Unknown command. Use /start to get the list of available commands",
		"ru": "\u041d\u0435\u0438\u0437\u0432\u0435\u0441\u0442\u043d\u0430\u044f \u043a\u043e\u043c\u0430\u043d\u0434\u0430. \u0418\u0441\u043f\u043e\u043b\u044c\u0437\u0443\u0439\u0442\u0435 /start \u0434\u043b\u044f \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u0441\u043f\u0438\u0441\u043a\u0430 \u0434\u043e\u0441\u0442\u0443\u043f\u043d\u044b\u0445 \u043a\u043e\u043c\u0430\u043d\u0434",
	},
	"GetMovieListError": {
		"en": "An error occurred while fetching the movie list. Please try again later",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0441\u043f\u0438\u0441\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u043e\u0432. \u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u043f\u043e\u043f\u0440\u043e\u0431\u0443\u0439\u0442\u0435 \u043f\u043e\u0437\u0436\u0435",
	},
	"MovieNotFound": {
		"en": "Movie not found",
		"ru": "\u0424\u0438\u043b\u044c\u043c \u043d\u0435 \u043d\u0430\u0439\u0434\u0435\u043d",
	},
	"GetFilesError": {
		"en": "Error retrieving files for the movie",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u0438 \u0444\u0430\u0439\u043b\u043e\u0432 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u043c\u0430",
	},
	"DeleteMovieDBError": {
		"en": "Error deleting the movie record from the database",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u0438 \u0437\u0430\u043f\u0438\u0441\u0438 \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u0437 \u0431\u0430\u0437\u044b \u0434\u0430\u043d\u043d\u044b\u0445",
	},
	"DeleteFilesDBError": {
		"en": "Error deleting the movie files from the database",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u0438 \u0444\u0430\u0439\u043b\u043e\u0432 \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u0437 \u0431\u0430\u0437\u044b \u0434\u0430\u043d\u043d\u044b\u0445",
	},
	"InvalidCommandFormat": {
		"en": "Invalid command format",
		"ru": "\u041d\u0435\u043f\u0440\u0430\u0432\u0438\u043b\u044c\u043d\u044b\u0439 \u0444\u043e\u0440\u043c\u0430\u0442 \u043a\u043e\u043c\u0430\u043d\u0434\u044b",
	},
	"MovieCheckError": {
		"en": "Error checking existence of movie: %v",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043e\u0432\u0430\u043d\u0438\u044f \u0444\u0438\u043b\u044c\u043c\u0430: %v",
	},
	"NotEnoughSpace": {
		"en": "Not enough space to download movie %s",
		"ru": "\u041d\u0435\u0434\u043e\u0441\u0442\u0430\u0442\u043e\u0447\u043d\u043e \u043c\u0435\u0441\u0442\u0430 \u0434\u043b\u044f \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0444\u0438\u043b\u044c\u043c\u0430 %s",
	},
	"DownloadStoppedLowSpeed": {
		"en": "Download of movie %s stopped due to low download speed",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u0438\u0437-\u0437\u0430 \u043d\u0438\u0437\u043a\u043e\u0439 \u0441\u043a\u043e\u0440\u043e\u0441\u0442\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438",
	},
	"VideoTitleError": {
		"en": "Error getting video title: %s",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u043e\u043b\u0443\u0447\u0435\u043d\u0438\u044f \u043d\u0430\u0437\u0432\u0430\u043d\u0438\u044f \u0432\u0438\u0434\u0435\u043e: %s",
	},
	"VideoDownloadError": {
		"en": "Error downloading video: %s",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0432\u0438\u0434\u0435\u043e: %s",
	},
	"VideoExists": {
		"en": "Video already exists or is in the process of downloading",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0443\u0436\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442 \u0438\u043b\u0438 \u0432 \u043f\u0440\u043e\u0446\u0435\u0441\u0441\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438",
	},
	"VideoDownloading": {
		"en": "Video is downloading!",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0441\u043a\u0430\u0447\u0438\u0432\u0430\u0435\u0442\u0441\u044f!",
	},
	"FileAlreadyExists": {
		"en": "File already exists",
		"ru": "\u0424\u0430\u0439\u043b \u0443\u0436\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u0443\u0435\u0442",
	},
	"StartCommand": {
		"en": "<file.torrent> - download torrent\n<URL> - download streaming video\n/ls - get list of files\n/rm <ID> - delete movie, all - to delete all\n/stop <ID> - stop download, all - to stop all",
		"ru": "<file.torrent> - \u0437\u0430\u0433\u0440\u0443\u0437\u0438\u0442\u044c torrent\n<URL> - \u0441\u043a\u0430\u0447\u0430\u0442\u044c \u043f\u043e\u0442\u043e\u043a\u043e\u0432\u043e\u0435 \u0432\u0438\u0434\u0435\u043e\n/ls - \u043f\u043e\u043b\u0443\u0447\u0438\u0442\u044c \u0441\u043f\u0438\u0441\u043e\u043a \u0444\u0430\u0439\u043b\u043e\u0432\n/rm <ID> - \u0443\u0434\u0430\u043b\u0438\u0442\u044c \u0444\u0438\u043b\u044c\u043c, all - \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u0438\u044f \u0432\u0441\u0435\u0445\n/stop <ID> - \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u0438\u0442\u044c \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0443, all - \u0434\u043b\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432\u0441\u0435\u0445",
	},
	"TorrentDownloadsStopped": {
		"en": "All downloads have been stopped!",
		"ru": "\u0412\u0441\u0435 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u044b!",
	},
	"NoMovies": {
		"en": "The list is empty",
		"ru": "\u0421\u043f\u0438\u0441\u043e\u043a \u043f\u0443\u0441\u0442",
	},
	"LoginSuccess": {
		"en": "Login successful",
		"ru": "\u0412\u0445\u043e\u0434 \u0432\u044b\u043f\u043e\u043b\u043d\u0435\u043d \u0443\u0441\u043f\u0435\u0448\u043d\u043e",
	},
	"AllMoviesDeleted": {
		"en": "All videos have been deleted",
		"ru": "\u0412\u0441\u0435 \u0432\u0438\u0434\u0435\u043e \u0443\u0434\u0430\u043b\u0435\u043d\u044b",
	},
	"MovieDownloaded": {
		"en": "ID: %d\nTitle: %s\nDownloaded: Yes\n\n",
		"ru": "ID: %d\n\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435: %s\n\u0417\u0430\u0433\u0440\u0443\u0436\u0435\u043d\u043e: \u0414\u0430\n\n",
	},
	"MovieDownloading": {
		"en": "ID: %d\nTitle: %s\nDownload Percentage: %d%%\n\n",
		"ru": "ID: %d\n\u041d\u0430\u0437\u0432\u0430\u043d\u0438\u0435: %s\n\u041f\u0440\u043e\u0446\u0435\u043d\u0442 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438: %d%%\n\n",
	},
	"DownloadProgress": {
		"en": "Downloading %s: %d%%",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 %s: %d%%",
	},
	"DownloadComplete": {
		"en": "Download of movie %s completed!",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u0437\u0430\u0432\u0435\u0440\u0448\u0435\u043d\u0430!",
	},
	"DownloadStopped": {
		"en": "Download of movie %s stopped by request",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0438\u043b\u044c\u043c\u0430 %s \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u0430 \u043f\u043e \u0437\u0430\u043f\u0440\u043e\u0441\u0443",
	},
	"VideoSuccessfullyDownloaded": {
		"en": "Video successfully downloaded: %s",
		"ru": "\u0412\u0438\u0434\u0435\u043e \u0443\u0441\u043f\u0435\u0448\u043d\u043e \u0437\u0430\u0433\u0440\u0443\u0436\u0435\u043d\u043e: %s",
	},
	"UnknownUser": {
		"en": "Please log in using the /login [PASSWORD] command",
		"ru": "\u0412\u044b\u043f\u043e\u043b\u043d\u0438\u0442\u0435 \u0432\u0445\u043e\u0434 \u0441 \u043f\u043e\u043c\u043e\u0449\u044c\u044e \u043a\u043e\u043c\u0430\u043d\u0434\u044b /login [PASSWORD]",
	},
	"DownloadDocumentError": {
		"en": "An error occurred while uploading the file (uploading files larger than 50MB is not available)",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0444\u0430\u0439\u043b\u0430 (\u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u0444\u0430\u0439\u043b\u043e\u0432 \u0431\u043e\u043b\u044c\u0448\u0435 50\u041c\u0411 \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u0430)",
	},
	"TorrentFileExistsError": {
		"en": "An error occurred while checking the existence of the file",
		"ru": "\u041f\u0440\u043e\u0438\u0437\u043e\u0448\u043b\u0430 \u043e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u043f\u0440\u043e\u0432\u0435\u0440\u043a\u0435 \u0441\u0443\u0449\u0435\u0441\u0442\u0432\u043e\u0432\u0430\u043d\u0438\u044f \u0444\u0430\u0439\u043b\u0430",
	},
	"TorrentFileDownloadError": {
		"en": "Error downloading torrent file",
		"ru": "\u041e\u0448\u0438\u0431\u043a\u0430 \u043f\u0440\u0438 \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0435 \u0442\u043e\u0440\u0440\u0435\u0442 \u0444\u0430\u0439\u043b\u0430",
	},
	"StopNoArgument": {
		"en": "Please specify the movie ID or 'all' to stop all downloads.",
		"ru": "\u041f\u043e\u0436\u0430\u043b\u0443\u0439\u0441\u0442\u0430, \u0443\u043a\u0430\u0436\u0438\u0442\u0435 ID \u0444\u0438\u043b\u044c\u043c\u0430 \u0438\u043b\u0438 'all' \u0434\u043b\u044f \u043e\u0441\u0442\u0430\u043d\u043e\u0432\u043a\u0438 \u0432\u0441\u0435\u0445 \u0437\u0430\u0433\u0440\u0443\u0437\u043e\u043a.",
	},
	"DownloadCancelled": {
		"en": "Download canceled: %s",
		"ru": "\u0417\u0430\u0433\u0440\u0443\u0437\u043a\u0430 \u043e\u0442\u043c\u0435\u043d\u0435\u043d\u0430: %s",
	},
	"InvalidIDs": {
		"en": "Invalid IDs: %s",
		"ru": "\u041d\u0435\u0432\u0430\u043b\u0438\u0434\u043d\u044b\u0435 ID: %s",
	},
	"DeletedMovies": {
		"en": "Deleted movies with IDs: %s",
		"ru": "\u0423\u0434\u0430\u043b\u0435\u043d\u044b \u0444\u0438\u043b\u044c\u043c\u044b \u0441 ID: %s",
	},
	"StoppedDownloads": {
		"en": "Stopped downloads for movie IDs: %s",
		"ru": "\u041e\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u044b \u0437\u0430\u0433\u0440\u0443\u0437\u043a\u0438 \u0434\u043b\u044f \u0444\u0438\u043b\u044c\u043c\u043e\u0432 \u0441 ID: %s",
	},
	"NoValidIDs": {
		"en": "No valid movie IDs provided",
		"ru": "\u041d\u0435 \u043f\u0440\u0435\u0434\u043e\u0441\u0442\u0430\u0432\u043b\u0435\u043d\u043e \u0432\u0430\u043b\u0438\u0434\u043d\u044b\u0445 ID \u0444\u0438\u043b\u044c\u043c\u043e\u0432",
	},
}
