#!/bin/bash

# Set paths to input and output files
INPUT_FILE="configs/messages.yaml"
OUTPUT_FILE="internal/lang/messages_gen.go"
PACKAGE_NAME="lang"

# Check if messages.yaml exists
if [ ! -f "$INPUT_FILE" ]; then
    echo "Error: $INPUT_FILE not found!"
    exit 1
fi

SUFFIX="MsgID"

# Create or clear the messages_gen.go file
echo "package $PACKAGE_NAME" > "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "// This file is automatically generated from messages.yaml" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "type MessageID string" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"
echo "const (" >> "$OUTPUT_FILE"

# Process messages.yaml and generate constants
awk -v suffix="$SUFFIX" '
BEGIN { FS=":"; OFS="" }
{
    if ($0 ~ /^[^ \t]/ && $0 !~ /^#/) {
        # Remove colons and spaces from the key
        gsub("[: ]", "", $1)
        key = $1
        # Replace dashes with underscores for valid Go identifiers
        gsub("-", "_", key)
        # Add suffix to the constant name
        const_name = key suffix
        print "    ", const_name, " MessageID = \"" key "\""
    }
}
' "$INPUT_FILE" >> "$OUTPUT_FILE"

echo ")" >> "$OUTPUT_FILE"

echo "File $OUTPUT_FILE has been successfully generated."
