name: golangci-lint
on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.22"

      - uses: golangci/golangci-lint-action@v6
        with:
          args: --timeout 5m
          version: v1.64.6 # renovate: datasource=github-releases depName=golangci/golangci-lint
